// Copyright (c) 2018 LockTrip
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef LOCKTRIP_ORACLE_H
#define LOCKTRIP_ORACLE_H

#include <string>
#include <map>
#include <cpp-ethereum/libdevcrypto/Common.h>
#include "util/contractabi.h"
#include "validation.h"
#include "contract-proxy.h"

static const dev::Address LockTripPriceOracleContract = dev::Address("0000000000000000000000000000000000000092");

static const std::string PRICE_ORACLE_CONTRACT_ABI = "[\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"isAdminSet\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"bool\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": false,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"admin\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"addNewAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"bool\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"nonpayable\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": false,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"admin\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"removeAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"bool\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"nonpayable\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t},\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"bytePriceInputsForAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"timeoutForAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"admins\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"bool\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"MIN_BYTE_PRICE\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint8\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"MIN_EXCHANGE_PRICE\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint8\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"MIN_GAS_PRICE\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint8\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"ACCUMULATE_HOURS\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint8\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"adminsArr\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": false,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"admin\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t},\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"backupAddress\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"setInitialAdmin\",\n"
                                                     "\t\t\"outputs\": [],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"nonpayable\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": false,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"a\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"setDgpAddress\",\n"
                                                     "\t\t\"outputs\": [],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"nonpayable\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t},\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"priceInputsForAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"priceInputsCounterForAdmin\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"exchangePrice\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"price\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"bytePrice\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"isDgpSet\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"bool\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"ONE_HOUR_TIMEOUT\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": true,\n"
                                                     "\t\t\"inputs\": [],\n"
                                                     "\t\t\"name\": \"dgp_address\",\n"
                                                     "\t\t\"outputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"\",\n"
                                                     "\t\t\t\t\"type\": \"address\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"view\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t},\n"
                                                     "\t{\n"
                                                     "\t\t\"constant\": false,\n"
                                                     "\t\t\"inputs\": [\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"newPrice\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t},\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"newBytePrice\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t},\n"
                                                     "\t\t\t{\n"
                                                     "\t\t\t\t\"name\": \"newExchangePrice\",\n"
                                                     "\t\t\t\t\"type\": \"uint256\"\n"
                                                     "\t\t\t}\n"
                                                     "\t\t],\n"
                                                     "\t\t\"name\": \"addPrice\",\n"
                                                     "\t\t\"outputs\": [],\n"
                                                     "\t\t\"payable\": false,\n"
                                                     "\t\t\"stateMutability\": \"nonpayable\",\n"
                                                     "\t\t\"type\": \"function\"\n"
                                                     "\t}\n"
                                                     "]";

enum price_oracle_contract_funcs {
    GET_EXCHANGE_PRICE = 15,
    GET_PRICE = 16,
    GET_BYTE_PRICE = 17
};

class PriceOracle : public ContractProxy {

public:
    PriceOracle();
    bool getPrice(uint64_t& gasPrice);
    bool getBytePrice(uint64_t& bytePrice);
};


#endif //LOCKTRIP_ORACLE_H
